language: python

env:
  - CI=True

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - python setup.py develop
  - make syntax
  - pytest --cov-report term-missing --cov=aioredlock -sv tests/ut
  - pytest -sv tests/acceptance

services:
  - redis-server

after_success:
  - codecov
